name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  library:
    runs-on: macos-12
    environment: default
    steps:
      - uses: actions/checkout@v2
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
      - name: Run Tests
        run: swift test --enable-code-coverage
      - name: Swift Coverage Report
        uses: maxep/spm-lcov-action@0.3.1
      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash) -X xcodellvm
